# file: roles/network/tasks/provision.yml

- name: Get Last Host Num
  register: host_last_num
  delegate_to: 127.0.0.1
  shell: echo {{ inventory_hostname }} | cut -d "." -f4

- name: Test Ipmi Link
  delegate_to: 127.0.0.1
  command: ipmitool -I lanplus -H {{ remote_prefix }}{{ host_last_num.stdout }} -U {{ ipmi_user }} -P {{ ipmi_passwd }} chassis power status

- name: Set boot dev
  delegate_to: 127.0.0.1
  command: ipmitool -I lanplus -H {{ remote_prefix }}{{ host_last_num.stdout }} -U {{ ipmi_user }} -P {{ ipmi_passwd }} chassis bootdev pxe
  when: host_last_num.stdout != "233"

- name: Begin To Provision
  delegate_to: 127.0.0.1
  command: ipmitool -I lanplus -H {{ remote_prefix }}{{ host_last_num.stdout }} -U {{ ipmi_user }} -P {{ ipmi_passwd }} chassis power reset
  when: enable_provision and  host_last_num.stdout != "233"
