# file: roles/common/tasks/host_related.yml

- name: 建立ssh目录
  file: dest=/root/.ssh mode=0700 state=directory
  when: method == "auth"

- name: 拷贝公钥
  template: src=authorized_keys.j2 dest=/root/.ssh/authorized_keys mode=0700
  when: method == "auth"
