# file: roles/common/tasks/host_related.yml


- name: 获取IP地址最后一位
  register: host_last_num
  shell: echo {{ inventory_hostname }} | cut -d "." -f4
  when: method == "do"

- name: 修复HostName
  hostname: name=server-{{ host_last_num.stdout }}
  when: method == "do"

- name: 修复Hosts文件
  template: src=f_hosts.j2 dest=/etc/hosts
  when: method == "do"

- name: 修改DNS文件
  template: src=resolv.conf.j2  dest=/etc/resolv.conf
  when: method == "do"

- name: 创建puppet目录
  file: dest=/etc/puppet mode=0755 state=directory
  when: method == "do"

- name: 创建Puppet配置文件
  template: src=puppet.conf.j2 dest=/etc/puppet/puppet.conf
  when: method == "do"

- name: 保证机器上的源是正确的
  yum: name=uos-release state=latest
  when: method == "do"

- name: Install ntp
  yum: name=ntpdate state=latest
  when: method == "do"

- name: 取消ntp开机启动
  service: name=ntpd state=stopped enabled=no
  when: method == "do"

- name: Sync time
  register: sync_time
  shell: /usr/sbin/ntpdate {{ ntp_server }}
  when: method == "do"
