# file: roles/system/tasks/package.yml

- name: 确认基本包已经被安装
  yum: name={{item}} state=latest
  with_items:
     - OpenIPMI
     - ipmitool
     - puppet
     - parted
  when: method == "do"

- name: 确认基本服务启动 
  shell: service ipmi start
  when: method == "ipmi"


- name: 确认基本服务开机启动
  shell: chkconfig ipmi on
  when: method == "ipmi"

