# define/create_cluster/003.provision_pre.do.yaml
#
#
- hosts: localhost
  gather_facts: no
  serial: 1
  roles:
    - { role: provision_pre, method: clean_dhcp }

- hosts:
    - Hypervisor
    - Network
    - Compute
    - Storage
  gather_facts: no
  serial: 1
  roles:
    - { role: provision_pre, method: physical }
