#Compute
# 是否让 Puppet 管理网卡的配置
sunfire::compute::manage_interface: true
# 将 nova/ceilometer/neutron 等服务的日志设为详细模式
sunfire::compute::verbose: true
# debug 模式
sunfire::compute::debug: false
# 是否启用计算节点 osd
sunfire::compute::enable_osd: false
# 是否安装 neutron
sunfire::compute::neutron: true
# neutron 用户的密码
sunfire::compute::neutron_user_password: '{{ service_db_password }}'
# VNC 代理的地址，一般为 l7 的地址或域名
sunfire::compute::vncproxy_host: 'lb.{{ domain }}'
nova::vncproxy::common::vncproxy_host: '{{ region_url }}'
# 管理网的 IP 地址
sunfire::compute::internal_address: "%{::ipaddress_eth0}"
# 加载到 neutron.ml2.mechanism_drivers 名称空间的驱动
# 此选项的值必须是数组（列表），且按先后顺序排序，可以包含下面这些值：
# logger, test, linuxbridge, openvswitch, hyperv, ncs, arista, cisco_nexus, l2population
# 默认为 ['openvswitch', 'linuxbridge'].
sunfire::compute::mechanism_drivers:
   - 'openvswitch'
# ceph monitor 的成员（域名）
sunfire::compute::mon_members: 'server-61.{{ domain }},server-62.{{ domain }},server-63.{{ domain }}'
# ceph monitor 的成员（IP 地址 ）
sunfire::compute::mon_hosts: '{{ manage_prefix }}61,{{ manage_prefix }}62,{{ manage_prefix }}63'
# Ceph 集群网络（osd 内部通信 ）
sunfire::compute::cluster_network: '{{ceph_prefix}}0/24'
# Ceph 集群网络（客户端与 Ceph Cluster 通信）
sunfire::compute::public_network: '{{ceph_prefix}}0/24'
sunfire::compute::eth2_gateway: '{{ ceph_gateway }}'
# 是否开启防火墙
sunfire::compute::enable_firewall: false
# 连接数据库的地址
sunfire::compute::db_host: 'lb.{{ domain }}'
# nova 数据账户的密码
sunfire::compute::nova_db_password: '{{ service_db_password }}'
# VNC 代理的 URL  地址
sunfire::compute::vncproxy_base_url: 'http://lb.{{ domain }}/vnc/RegionOne/vnc_auto.html'
# OSD 日志大小
sunfire::compute::osd_journal_size: 14336
# libvirt 镜像的 rbd 池名称
sunfire::compute::libvirt_images_rbd_pool: 'openstack-00'
# ceilometer 的密码
sunfire::compute::auth_password: '{{ service_db_password }}'
# 是否使用持久化消息队列
sunfire::compute::rpc_msg_persistence: true
sunfire::compute::network_eth2_prefix: '{{ ceph_prefix }}'
sunfire::compute::network_eth3_prefix: '{{ network_prefix }}'
sunfire::monitor::ceph::client: '{{ manage_prefix }}247'
nova::compute::config_drive_format:  'iso9660'
nova::compute::force_config_drive: true
# neutron 隧道的类型（列表）
openstack::neutron::tunnel_types:
  - 'vxlan'
# HA 在配置文件中配置多个 rabbit MQ  的地址
sunfire::compute::rabbit_hosts:
  - '{{ manage_prefix }}44:5672'
  - '{{ manage_prefix }}45:5672'
  - '{{ manage_prefix }}46:5672'

nova::network::neutron::vif_plugging_is_fatal: false
nova::network::neutron::vif_plugging_timeout: 0

nova::nova_public_key:
  type: 'ssh-rsa'
  key: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDIOLMkcR8Txxh9x7njXTJSvwfgZX+oisBm9VZg7WthnF7WfAV1MNwU5XoIKS8f7xUBwANwy16R3Se9yxFI97qnOcs7e/CA4iQIsq81pFnXqWJHB1e7+IFfFjQHqvC96E0LyHvpQXlKrNjMZz22JNwI9lTXqdMdCpuRBYXqDXetSttLd5um19wYzbyItWwq2hbG9a5DFU5KpyQrz5UQltpJVF/GlMlvSUqDcaSFdgoScWZmPOe/JZT5/s03F1Ui1xST+G+1U4x4Dd+13wY/MqoRs4/bm1hOzQ+ZVrb6XqAdg92dBuFZRTetQKY1ICrQhPSsN7ZA1VbOmfk/qG323V8h'
nova::nova_private_key:
  type: 'ssh-rsa'
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAyDizJHEfE8cYfce5410yUr8H4GV/qIrAZvVWYO1rYZxe1nwF
    dTDcFOV6CCkvH+8VAcADcMtekd0nvcsRSPe6pznLO3vwgOIkCLKvNaRZ16liRwdX
    u/iBXxY0B6rwvehNC8h76UF5SqzYzGc9tiTcCPZU16nTHQqbkQWF6g13rUrbS3eb
    ptfcGM28iLVsKtoWxvWuQxVOSqckK8+VEJbaSVRfxpTJb0lKg3GkhXYKEnFmZjzn
    vyWU+f7NNxdVItcUk/hvtVOMeA3ftd8GPzKqEbOP25tYTs0PmVa2+l6gHYPdnQbh
    WUU3rUCmNSAq0IT0rDe2QNVWzpn5P6ht9t1fIQIDAQABAoIBAH+B3FPw1mG6ARbZ
    AsCQsWOQ1GtLOCkVc8Idq4y+pgvbkWn2QWOIYh/MpBJeZ+xmTXJ33bkPSoKJ3K05
    jSBy4yNr4slW/KqXWWtQn9QBflWhQT0KqAzFDV6IvUnEytul/KrsWj0JvTyZJtfF
    R7+faaErfox5UkDEaJ3KbqXHPdfVG0l7T8baqJNwJvgFT5nO78X1Tb48R2Ps7BCD
    RkumK9bJnbDl9lJHVsvnex3jyjuEYhv+UZBT2GIZ3+zaj27KrJUMs58+7D+mMOep
    fwV4O3PhD+P5xBzDoJYtMnkm+BkPMQ4UOEB1UBHtoVOdV5UeRYfe84r4rwRplb2U
    20R6QYECgYEA7/YB3QpRL5LKUFujPzdcrufrE7125P5Jl4NW60Se8uDNrS9eqksh
    UPqqUSdlAE5tBJUrLx1JsJ7zYH3VAxDdsvRew+l5f6p68KQinUtd9pEj1iTxK213
    FyrodF5DVimmuJecZxW/MadVnjPpez49XOKbfSPox868K2Q3Elmddr0CgYEA1Zq0
    8ICwMOC9bvjVelcpJGsnuosNnonS+Y+YwzjHbPKHEA3j4nCSsjcWSS1MHjt2fDbW
    p883QbM1zx4VWIoJTvp4ftLaa8/dhHPcqEJyNhosSSoRazVlGbCj4911nqXYqo7t
    gXLLD/Ciuw4HdeYOT8N/fvo0lOfeCUlYLfh8kjUCgYAaNl5XvgPGVZuiEZCQnESU
    mqL0QhMVyq1RTriU9KcEUwhErdMCeTiHdwpZ2RrQYMDJ6l2QRPvCvmpJlRVKw3Hk
    VYtwjTWHe6D4XoWldxEpmQs4Hkr1+nwy3K4N4Cos5Fng+jbMj/SVwPi6UmNj4hWj
    6uEfV2fbQ7sMZmMZrw5jZQKBgA13p5jSREmQoeDxR2RjQnDNYL/eLImmXurlJtiI
    J+qyj9lvRsLsHhOmbX1Hodj2Hs5OFtKVugImbmoUl3vxmAymthoo6SSLAohrVao2
    JkVK+SfTwy1jPHCWNn8TY2sRQcvfHxJeTnc+0MPCaq4ARz64ML2swMvyookrWqfr
    Vs9RAoGBANCE6bLy7ujEePL9CFyBlhIV8L+qA/TuYFj4g7D0+pdJUY7t7eVdPYhC
    vPjzIpq4EiV+J/Zy/tdg7KSEdfjcvuiDhLzDOXIl6ueKrgOfI1i1eP9mtRW7ueHh
    TDADn4kEyxXVgc2NaZt/53aHZbe+9hN4I2UJBbBewwaCaiLX5Xm4
    -----END RSA PRIVATE KEY-----

# Network
neutron::agents::ml2::ovs::enable_tunneling: true
# 这个参数是openvswitch的local_ip，如果SDN网卡不是eth3，请把下面的eth3改为正确的网卡
neutron::agents::ml2::ovs::local_ip: "%{::ipaddress_eth3_{{ network_vlan }}}"
neutron::agents::ml2::ovs::bridge_mappings:
  - 'physnet3:ovsbr3'
neutron::agents::ml2::ovs::tunnel_types:
  - vxlan
neutron::config::ovs_agent_config:
  agent/ovsdb_monitor_respawn_interval:
    value: 30
  securitygroup/enable_security_group:
    value: true
