---

hostname: puppet
domain: example.com
manager_network: 10.0.215.0/24

tenant_network: 10.0.215.0/24
tenant_vlan_id: 1124
tenant_nic: eth2 

storage_network: 10.0.215.0/24
storage_vlan_id: 1116
storage_nic: eth3

local_ip: 10.0.215.31

puppet_server_name: foreman.example.com
puppet_server_ip: 10.0.215.31

node_map:
  - hypervisor_node:
      - 10.0.215.[31:33]
  - controller_node:
      - 10.0.215.[41:43]
  - network_node:
      - 10.0.215.[64:65]
  - compute_node:
      - 10.0.215.[68:70]
   
  - loaderbalance_node:
      - 10.0.215.[34:36]
  - rabbitmq_node:
      - 10.0.215.[44:46]
  - cache_node:
      - 10.0.215.[47:48]
  - mysql_node:
      - 10.0.215.[50:52]
  - ceph_monitor_node:
      - 10.0.215.[61:63]

  - localhost:
      - 10.0.215.31
  - vip_address:
      - 10.0.215.37
  - puppet_server_ip:
      - 10.0.215.31

dhcp_proxy: true
dhcp_interface: br0
dhcp_gateway: 10.0.215.1
foreman_base_url: http://10.0.215.1

mac_map:
  - 10.0.215.32: 00:00:00:00
  - 10.0.215.33: 00:00:00:00
  - 10.0.215.64: 00:00:00:00
  - 10.0.215.65: 00:00:00:00
  - 10.0.215.68: 00:00:00:00
  - 10.0.215.69: 00:00:00:00
  - 10.0.215.70: 00:00:00:00

#####################################################
####### You don't have to change this parts##########
#####################################################
server_environments:
    - newton

db_password: 'ustack'
admin_password: 'ustack'
logging_level: 'debug'

enable_foreman: true
enable_foreman_proxy: true
enable_yumrepo: true
enable_ntpserver: true
enable_install_deploy_tools: true

scriptdir: /root/ctask/install
puppetdb::globals::version: 2.3.8-1.el7
postgresql::globals::version: '9.4'
apache::default_vhost: false
apache::purge_configs: false
foreman_proxy::dhcp: true
foreman_proxy::register_in_foreman: false
