# file:  roles/cluster/tasks/create.yml

- name: add foreman hosts
  shell: curl {{ global_parameter.foreman_server.ip }}:8080/add_hosts -X POST -d 'cluster_name={{ domain }}' -d 'hosts={{ groups["Hypervisor"] }}'
  delegate_to: 127.0.0.1
