# file:  roles/cluster/tasks/main.yml

- name: Create hieradata directory
  file: dest=/etc/puppet/hieradata/{{ domain }}/common mode=755 state=directory
  delegate_to: "{{ global_parameter.puppet_server.ip }}"

- name: Create common hieradata
  template: src={{ item }} dest=/etc/puppet/hieradata/{{ domain }}/{{ item }}
  delegate_to: "{{ global_parameter.puppet_server.ip }}"
  with_items:
      - common/base.yaml
      - common/api.yaml
      - common/ceph.yaml
      - common/compute.yaml
      - common/db.yaml
      - common/hypervisor.yaml
      - common/l4.yaml
      - common/mq.yaml
      - common/network.yaml
      - common/package.yaml

- name: Create hypervisor hieradata
  template: src={{ item }} dest=/etc/puppet/hieradata/{{ domain }}/{{ item }}
  delegate_to: "{{ global_parameter.puppet_server.ip }}"
  with_items:
       - server-31.yaml
       - server-32.yaml
       - server-33.yaml

- name: Create VM hieradata
  template: src={{ item }} dest=/etc/puppet/hieradata/{{ domain }}/{{ item }}
  delegate_to: "{{ global_parameter.puppet_server.ip }}"
  with_items:
       - server-34.yaml
       - server-41.yaml
       - server-42.yaml
       - server-43.yaml
       - server-47.yaml
       - server-48.yaml
       - server-50.yaml

- name: Create Network node hieradata
  template: src={{ item }} dest=/etc/puppet/hieradata/{{ domain }}/{{ item }}
  delegate_to: "{{ global_parameter.puppet_server.ip }}"
  with_items:
      - server-64.yaml
      - server-65.yaml
      - server-66.yaml
