# file: roles/software/tasks/node_definition.yml

- name: 生成Node Definition
  delegate_to: "{{ real_puppet_server }}"
  register: node_definition
  template: src=node_definition.j2 dest=/etc/puppet/environments/{{ puppet_env }}/manifests/cluster/{{ domain_region }}.pp
