# file: roles/software/tasks/node_definition.yml

- name: Create node Definition
  delegate_to: "{{ global_parameter.puppet_server.ip }}"
  register: node_definition
  template: src=node_definition.j2 dest=/etc/puppet/environments/{{ puppet_env }}/manifests/cluster/{{ domain }}.pp
